import React from 'react';

/**
 * ExportToolbar — P2 #11 Exportable Client Report Component
 *
 * Provides:
 *  1. "Print / Save PDF" — Triggers window.print() styled via @media print
 *  2. "Download Markdown" — Generates and downloads GeoAuditor-Report.md
 */
export default function ExportToolbar({ data, type = 'single' }) {
  if (!data) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    let md = '';

    if (type === 'multi') {
      const summary = data.summary || {};
      const brand = data.brand || 'Brand';
      const competitorScores = data.overallScore?.competitors || [];
      const perQuery = data.perQuery || [];

      md = `# GEO Auditor — Multi-Query Visibility Report

**Target Brand:** ${brand}  
**Aggregate GEO Score:** ${summary.brandScore || 0}%  
**Audit Date:** ${new Date(data.timestamp || Date.now()).toLocaleString()}  
**Demo Sandbox Mode:** ${data.demoMode ? 'Active' : 'Live'}

---

## Executive Summary
- **Visibility Score:** ${summary.brandScore || 0}% (${summary.brandVisibleIn || 0} of ${summary.totalQueries || 0} queries visible)
- **Top Competitor Benchmark:** ${summary.bestCompetitor || 'N/A'} (${summary.bestCompetitorScore || 0}%)

## Competitor Scores
| Entity Name | Visibility Score | Queries Visible |
| :--- | :---: | :---: |
| **${brand}** | **${summary.brandScore || 0}%** | **${summary.brandVisibleIn || 0}/${summary.totalQueries || 0}** |
${competitorScores.map(c => `| ${c.name} | ${c.score}% | ${c.visibleIn}/${summary.totalQueries || 0} |`).join('\n')}

## Per-Query Visibility Matrix
| Target Search Query | Brand Status | Competitors Status |
| :--- | :---: | :---: |
${perQuery.map(q => `| "${q.query}" | ${q.brand?.found ? 'VISIBLE' : 'MISSING'} | ${q.competitors?.map(c => `${c.name}: ${c.found ? 'Yes' : 'No'}`).join(', ') || 'N/A'} |`).join('\n')}

---
*Generated by GEO Auditor — Powered by SerpApi (AI Overview, AI Mode, Google Search APIs)*
`;
    } else {
      const brand = data.brand || {};
      const brandName = brand.name || 'Brand';
      const competitors = data.competitors || [];
      const brandFound = brand.aiOverview?.found || brand.aiMode?.found;
      const gapAnalysis = data.gapAnalysis || {};
      const recommendations = data.recommendations || [];

      md = `# GEO Auditor — Generative Engine Optimization Report

**Target Brand:** ${brandName}  
**Target Query:** "${data.query || ''}"  
**Brand Status:** ${brandFound ? 'VISIBLE' : 'MISSING'}  
**Audit Date:** ${new Date(data.timestamp || Date.now()).toLocaleString()}  
**Demo Sandbox Mode:** ${data.demoMode ? 'Active' : 'Live'}

---

## 1. Competitor Visibility Matrix
| Entity Name | Type | AI Overview | AI Mode | Overall Status |
| :--- | :---: | :---: | :---: | :---: |
| **${brandName}** | Target Brand | ${brand.aiOverview?.found ? 'Found' : 'Missing'} | ${brand.aiMode?.found ? 'Found' : 'Missing'} | **${brandFound ? 'VISIBLE' : 'MISSING'}** |
${competitors.map(c => `| ${c.name} | Competitor | ${c.aiOverview?.found ? 'Found' : 'Missing'} | ${c.aiMode?.found ? 'Found' : 'Missing'} | ${c.aiOverview?.found || c.aiMode?.found ? 'VISIBLE' : 'MISSING'} |`).join('\n')}

## 2. Structural Gap Analysis (Why You're Missing)
${gapAnalysis.structuralGaps && gapAnalysis.structuralGaps.length > 0
  ? gapAnalysis.structuralGaps.map(g => `### [${g.severity.toUpperCase()}] ${g.title}\n${g.explanation}\n`).join('\n')
  : 'No major structural gaps identified. Strong organic search positioning.'}

## 3. Prioritized Recommendations
${recommendations.length > 0
  ? recommendations.map(r => `**${r.priority}. ${r.action}** (Impact: ${r.impact.toUpperCase()}, Effort: ${r.effort.toUpperCase()})\n- ${r.detail}\n`).join('\n')
  : 'Maintain current content optimization and monitor competitor AI updates.'}

---
*Generated by GEO Auditor — Powered by SerpApi (AI Overview, AI Mode, Google Search APIs)*
`;
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `GeoAuditor-Report-${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="export-toolbar no-print">
      <div className="export-toolbar__label">
        <span className="material-symbols-outlined text-[16px]">file_download</span>
        <span>Export Audit Report</span>
      </div>
      <div className="export-toolbar__actions">
        <button
          type="button"
          className="chip-btn chip-btn--active"
          onClick={handlePrint}
        >
          <span className="material-symbols-outlined text-[14px]" style={{ marginRight: '4px' }}>print</span>
          Print / Save PDF
        </button>
        <button
          type="button"
          className="chip-btn"
          onClick={handleDownloadMarkdown}
        >
          <span className="material-symbols-outlined text-[14px]" style={{ marginRight: '4px' }}>download</span>
          Download Markdown (.md)
        </button>
      </div>
    </div>
  );
}
