import React from 'react';

/**
 * ExportToolbar — P2 #11 Exportable Client Report Component
 *
 * Provides:
 *  1. "Print / Save PDF" — Triggers window.print() styled via @media print
 *  2. "Download Markdown" — Generates and downloads GeoAuditor-Report.md
 */
export default function ExportToolbar({ data, type = 'single' }) {
  if (!data) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    let md = '';

    if (type === 'multi') {
      const summary = data.summary || {};
      const brand = data.brand || 'Brand';
      const competitorScores = data.overallScore?.competitors || [];
      const perQuery = data.perQuery || [];

      md = `# GEO Auditor — Multi-Query Visibility Report

**Target Brand:** ${brand}  
**Aggregate GEO Score:** ${summary.brandScore || 0}%  
**Audit Date:** ${new Date(data.timestamp || Date.now()).toLocaleString()}  
**Demo Sandbox Mode:** ${data.demoMode ? 'Active' : 'Live'}

---

## Executive Summary
- **Visibility Score:** ${summary.brandScore || 0}% (${summary.brandVisibleIn || 0} of ${summary.totalQueries || 0} queries visible)
- **Top Competitor Benchmark:** ${summary.bestCompetitor || 'N/A'} (${summary.bestCompetitorScore || 0}%)

## Competitor Scores
| Entity Name | Visibility Score | Queries Visible |
| :--- | :---: | :---: |
| **${brand}** | **${summary.brandScore || 0}%** | **${summary.brandVisibleIn || 0}/${summary.totalQueries || 0}** |
${competitorScores.map(c => `| ${c.name} | ${c.score}% | ${c.visibleIn}/${summary.totalQueries || 0} |`).join('\n')}

## Per-Query Visibility Matrix
| Target Search Query | Brand Status | Competitors Status |
| :--- | :---: | :---: |
${perQuery.map(q => `| "${q.query}" | ${q.brand?.found ? 'VISIBLE' : 'MISSING'} | ${q.competitors?.map(c => `${c.name}: ${c.found ? 'Yes' : 'No'}`).join(', ') || 'N/A'} |`).join('\n')}

---
*Generated by GEO Auditor — Powered by SerpApi (AI Overview, AI Mode, Google Search APIs)*
`;
    } else {
      const brand = data.brand || {};
      const brandName = brand.name || 'Brand';
      const competitors = data.competitors || [];
      const brandFound = brand.aiOverview?.found || brand.aiMode?.found;
      const gapAnalysis = data.gapAnalysis || {};
      const recommendations = data.recommendations || [];

      md = `# GEO Auditor — Generative Engine Optimization Report

**Target Brand:** ${brandName}  
**Target Query:** "${data.query || ''}"  
**Brand Status:** ${brandFound ? 'VISIBLE' : 'MISSING'}  
**Audit Date:** ${new Date(data.timestamp || Date.now()).toLocaleString()}  
**Demo Sandbox Mode:** ${data.demoMode ? 'Active' : 'Live'}

---

## 1. Competitor Visibility Matrix
| Entity Name | Type | AI Overview | AI Mode | Overall Status |
| :--- | :---: | :---: | :---: | :---: |
| **${brandName}** | Target Brand | ${brand.aiOverview?.found ? 'Found' : 'Missing'} | ${brand.aiMode?.found ? 'Found' : 'Missing'} | **${brandFound ? 'VISIBLE' : 'MISSING'}** |
${competitors.map(c => `| ${c.name} | Competitor | ${c.aiOverview?.found ? 'Found' : 'Missing'} | ${c.aiMode?.found ? 'Found' : 'Missing'} | ${c.aiOverview?.found || c.aiMode?.found ? 'VISIBLE' : 'MISSING'} |`).join('\n')}

## 2. Structural Gap Analysis (Why You're Missing)
${gapAnalysis.structuralGaps && gapAnalysis.structuralGaps.length > 0
  ? gapAnalysis.structuralGaps.map(g => `### [${g.severity.toUpperCase()}] ${g.title}\n${g.explanation}\n`).join('\n')
  : 'No major structural gaps identified. Strong organic search positioning.'}

## 3. Prioritized Recommendations
${recommendations.length > 0
  ? recommendations.map(r => `**${r.priority}. ${r.action}** (Impact: ${r.impact.toUpperCase()}, Effort: ${r.effort.toUpperCase()})\n- ${r.detail}\n`).join('\n')
  : 'Maintain current content optimization and monitor competitor AI updates.'}

---
*Generated by GEO Auditor — Powered by SerpApi (AI Overview, AI Mode, Google Search APIs)*
`;
    }

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `GeoAuditor-Report-${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="export-toolbar no-print">
      <div className="export-toolbar__label">
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{ flexShrink: 0, color: 'var(--primary)' }}>
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
          <polyline points="14 2 14 8 20 8" />
          <line x1="16" y1="13" x2="8" y2="13" />
          <line x1="16" y1="17" x2="8" y2="17" />
          <polyline points="10 9 9 9 8 9" />
        </svg>
        <span>Export Audit Report</span>
      </div>
      <div className="export-toolbar__actions">
        <button
          type="button"
          className="export-btn export-btn--primary"
          onClick={handlePrint}
          title="Print or Save complete audit report as PDF"
        >
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{ flexShrink: 0 }}>
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          <span>Print / Save PDF</span>
        </button>
        <button
          type="button"
          className="export-btn export-btn--secondary"
          onClick={handleDownloadMarkdown}
          title="Download report in Markdown format"
        >
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={{ flexShrink: 0 }}>
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          <span>Download Markdown (.md)</span>
        </button>
      </div>
    </div>
  );
}
